# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Does not insert a blank line between shell prompts
add_newline = false

format = """
$username\
$directory\
$lua\
$rust\
$python\
$rlang\
$character\
"""

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green) ' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[battery]
disabled = true

[username]
disabled = false
style_user = 'white bold'
style_root = 'red bold'
format = '\[[$user]($style)\] '
show_always = true

[hostname]
ssh_only = true

[directory]
truncation_length = 1
disabled = false

[env_var]
disabled = true

[lua]
format = 'on [ $version](bold blue)'

[rust]
format = 'on [ $version](red bold)'

[python]
python_binary = 'python3'
symbol = ''
format = 'on [${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rlang]
symbol = 'ﳒ'
format = 'on [$symbol ($version)]($style)'
detect_extensions = ['R', 'r', 'Rd', 'Rmd', 'rmd', 'Rproj', 'Rsx']

