-- first, set leader to <space>
vim.keymap.set("", "<Space>", "<Nop>", { silent = true })
vim.g.mapleader = " "
vim.keymap.set("i", "ii", "<Esc>", { silent = true }) -- leave insert mode with "ii"
require("user.options")
-- require("user.colorscheme")
-- require("user.alpha")
require("user.plugins_lazy")
require("user.autocmds")
require("user.globals")
-- require("user.autopairs")
--[[ require("user.bufferline") ]]
-- require("user.cmp")
-- require("user.comment")
-- require("user.dap")
-- require("user.gitsigns")
-- require("user.illuminate")
-- require("user.impatient")
-- require("user.indentline")
-- require("user.plugins")
-- require("user.lsp")
-- require("user.nvim-tree")
-- require("user.statusline")
-- require("user.telescope")
-- require("user.toggleterm")
-- require("user.treesitter")
-- require("user.vimtex")
-- require("user.whichkey")
